apiVersion: batch/v1beta1
kind: ScheduledJob
metadata:
  name: my-scheduledjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            image: my-job-image
            command: ["sh", "-c", "echo Hello, ScheduledJob!"]
          restartPolicy: OnFailure
