apiVersion: v1
kind: PersistentVolume
metadata:
  name: fiap-pv-scraping
  labels:
    name: fiap-pv-scraping
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-db
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /fiap/kubernetes_2/aula_1/data