apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    name: db-config
data:
  MONGO_URL: mongodb://a153b0027bb0e41a796e5eb6f9bf9c46-1423994784.us-east-1.elb.amazonaws.com:27017/db_fiap